version: '3'
services:
  web:
    container_name: php-apache
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASS=passw0rd
      - DATABASE_NAME=perfect_php
    ports:
      - 9000:80
    links:
      - db
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
